# Make sure to fill in your spotify client_secret information
spotify_token = "BQDuIsKzxP-DfAW7vj5UO4Mcz8XGotHgLvst6YgGNALXWiBBCBUk0-ILxo918tMlJNaKiNOhj4nuFu4XWBlRzjagf2Js9AhYK0yR2CLI4H-KsNRNhfm_xML7LYahfM0-i9yXwhDVw9l32pN0DSrt8lytdxZ5K9EzfBFWuP_LjP8"
spotify_user_id = "ygbankz"
